Feature/api
CrsPet/TaskManager pull request #14
Opened 2022-10-20 17:08 UTC by CrsPet

2022-10-20 18:17 UTC, greybutton requested changes

2022-10-20 18:17 UTC, greybutton commented on test/factories/tasks.rb
> +    expired_at { nil }
почему nil?

2022-10-20 20:57 UTC, CrsPet commented on test/factories/tasks.rb
> +    expired_at { nil }
Тест не проходил, не разобрался сразу в чем проблема.
Сейчас осознал в чем была загвоздка (В params контроллера не было разрешено поле expired_at)

2022-10-21 06:37 UTC, greybutton approved these changes

2022-10-21 13:01 UTC, merged