Feature/tasks
CrsPet/TaskManager pull request #17
Opened 2022-10-26 11:25 UTC by CrsPet

2022-10-27 18:29 UTC, greybutton requested changes

2022-10-27 18:29 UTC, greybutton commented on app/controllers/api/v1/application_controller.rb
> +  respond_to :json, :js
почему :js?

2022-10-27 18:29 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +    search.sorts = ransack_sort_params
не понял, зачем это?

2022-10-27 18:29 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.jsx
> +  const loadColumnMore = (state, page = 1, perPage = 9) => {
почему perPage = 9?

2022-10-27 18:29 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +    fetched_task.update(task_params)
почему fetched_task?

2022-10-27 18:29 UTC, greybutton commented on app/javascript/components/ColumnHeader/ColumnHeader.js
> +  }, [count === totalCount]);
тут useEffect выглядит лишним, можно как обычную переменную рассчитать

2022-10-27 18:29 UTC, greybutton commented on app/javascript/components/ColumnHeader/ColumnHeader.js
> +        {show ? (
чтобы не писать `: null` можно сделать `show && (`

2022-10-27 18:29 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.jsx
> +import AddIcon from '@mui/icons-material/Add';
смешанные импорты пакетов и локальный файлы

2022-10-27 18:29 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.jsx
> +          cards: [...boardCards[state].cards, ...data.items],
при обновлении стейта на основе предыдущего лучше использовать prevState

2022-10-27 18:29 UTC, greybutton commented on app/javascript/packs/application.js
> += require js-routes
уверен что это надо?

2022-10-27 18:29 UTC, greybutton commented on config/application.rb
> +    # config.web_console.permissions = '172.18.0.1'
зачем?

2022-10-27 18:29 UTC, greybutton commented on db/seeds.rb
> +task = Task.find_or_create_by(name: 'task', author_id: 3, assignee_id: 2, state: 'new_task')
откуда 3 и 2 ид?

2022-10-27 18:29 UTC, greybutton commented on package.json
> +    "ramda": "^0.28.0",
не хваттает qs пакета

2022-10-27 18:29 UTC, greybutton commented on package.json
> +    "@mui/material": "^5.10.10",
используй только 4 версию

2022-10-27 18:29 UTC, greybutton commented on package.json
> +    "@emotion/styled": "^11.10.4",
это для чего?

2022-10-27 18:54 UTC, CrsPet commented on app/controllers/api/v1/tasks_controller.rb
> +    search.sorts = ransack_sort_params
Необходимо было добавить сортировку, нашел в документации, как это сделать :
https://activerecord-hackery.github.io/ransack/getting-started/sorting/#sorting-in-the-controller

Код, который был написан ранее, не выполнял сортировку.

2022-10-27 19:03 UTC, CrsPet commented on app/javascript/components/TaskBoard/TaskBoard.jsx
> +  const loadColumnMore = (state, page = 1, perPage = 9) => {
Менял на разные значения, смотрел, как отрабатывает. Верну значение 10.

2022-10-27 19:16 UTC, CrsPet commented on app/controllers/api/v1/application_controller.rb
> +  respond_to :json, :js
ошибка, исправлю

2022-10-27 19:22 UTC, CrsPet commented on app/controllers/api/v1/tasks_controller.rb
> +    fetched_task.update(task_params)
Менял, так как добавлял логику в этот эндпоинт, которая в итоге оказалась излишней.
---
Верну прежнее название.

2022-10-27 19:50 UTC, CrsPet commented on db/seeds.rb
> +task = Task.find_or_create_by(name: 'task', author_id: 3, assignee_id: 2, state: 'new_task')
id manager и developer соответственно, Исправлю, чтобы это было явно видно.

2022-10-27 20:47 UTC, CrsPet commented on package.json
> +    "@emotion/styled": "^11.10.4",
Браузер ругался, в консоли выдавало ошибку Uncaught Error: Cannot find module

2022-10-28 17:53 UTC, greybutton commented on app/javascript/components/ColumnHeader/ColumnHeader.js
> +  const show = !(count === totalCount);
в жс обычно пишут так `count !== totalCount`

2022-10-28 17:53 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +    search.sorts = ransack_sort_params
хорошо, что нашли в документации, но надо поискать другой способ, чтобы через ransack_params работало

2022-10-29 19:27 UTC, greybutton approved these changes

2022-10-29 19:35 UTC, merged